### ISSUE TITLE
Assorted issues after major facetization overhaul

### ISSUE THREAD

**Issue by Cervator** [Terasology/Cities#22]
@msteiger - I figure you're aware of most/all of this already and it is on a list somewhere but just in case I ran into anything useful posting some details I got from testing :-)

House generated on wrong side of city wall, slightly overlapping (few other houses did the same but from the inside):

![terasology-150919150810-1152x720](https://cloud.githubusercontent.com/assets/1063833/9977884/79c67ce0-5ee5-11e5-8e52-7e00dbc61c28.jpg)

After visiting a few cities I found one that broke on a structure (maybe?) and permanently left some chunks partially generated and invisible (even if I traveled away and came back). Screenie:

![terasology-150919150956-1152x720](https://cloud.githubusercontent.com/assets/1063833/9977886/9e856118-5ee5-11e5-8183-9f435ab98331.jpg)

Big log snippet: 

```
15:07:54.834 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.logic.location.LocationComponent) over an existing component for entity 8904
15:07:56.462 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.logic.location.LocationComponent) over an existing component for entity 8974
15:08:11.072 [Engine-Task-Pool] INFO  o.t.r.opengl.LwjglRenderingProcess - Screenshot 'Terasology-150919150810-1152x720.jpg' saved! 
15:08:14.118 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
15:08:14.122 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
15:08:15.053 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.logic.location.LocationComponent) over an existing component for entity 10327
15:08:17.771 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
15:08:18.587 [Chunk-Generator-7] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-7
java.lang.IllegalArgumentException: Out of bounds: (1184, 332) for region (x=1152 y=320 w=32 h=32)
	at org.terasology.world.generation.facets.base.BaseFacet2D.getWorldIndex(BaseFacet2D.java:55) ~[classes/:na]
	at org.terasology.world.generation.facets.base.BaseFieldFacet2D.getWorld(BaseFieldFacet2D.java:48) ~[classes/:na]
	at org.terasology.cities.walls.TownWallRasterizer$1.apply(TownWallRasterizer.java:55) ~[na:na]
	at org.terasology.cities.raster.Pens$2.draw(Pens.java:64) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawClippedLine(RasterUtil.java:166) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawLine(RasterUtil.java:147) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.rasterSolid(TownWallRasterizer.java:79) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.generateChunk(TownWallRasterizer.java:64) ~[na:na]
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:67) ~[classes/:na]
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:75) ~[classes/:na]
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:661) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:08:18.614 [Chunk-Generator-0] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-0
java.lang.IllegalArgumentException: Out of bounds: (1184, 332) for region (x=1152 y=320 w=32 h=32)
	at org.terasology.world.generation.facets.base.BaseFacet2D.getWorldIndex(BaseFacet2D.java:55) ~[classes/:na]
	at org.terasology.world.generation.facets.base.BaseFieldFacet2D.getWorld(BaseFieldFacet2D.java:48) ~[classes/:na]
	at org.terasology.cities.walls.TownWallRasterizer$1.apply(TownWallRasterizer.java:55) ~[na:na]
	at org.terasology.cities.raster.Pens$2.draw(Pens.java:64) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawClippedLine(RasterUtil.java:166) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawLine(RasterUtil.java:147) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.rasterSolid(TownWallRasterizer.java:79) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.generateChunk(TownWallRasterizer.java:64) ~[na:na]
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:67) ~[classes/:na]
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:75) ~[classes/:na]
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:661) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:08:18.675 [Chunk-Generator-7] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-7
java.lang.IllegalArgumentException: Out of bounds: (1184, 332) for region (x=1152 y=320 w=32 h=32)
	at org.terasology.world.generation.facets.base.BaseFacet2D.getWorldIndex(BaseFacet2D.java:55) ~[classes/:na]
	at org.terasology.world.generation.facets.base.BaseFieldFacet2D.getWorld(BaseFieldFacet2D.java:48) ~[classes/:na]
	at org.terasology.cities.walls.TownWallRasterizer$1.apply(TownWallRasterizer.java:55) ~[na:na]
	at org.terasology.cities.raster.Pens$2.draw(Pens.java:64) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawClippedLine(RasterUtil.java:166) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawLine(RasterUtil.java:147) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.rasterSolid(TownWallRasterizer.java:79) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.generateChunk(TownWallRasterizer.java:64) ~[na:na]
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:67) ~[classes/:na]
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:75) ~[classes/:na]
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:661) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:08:18.793 [Chunk-Generator-3] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-3
java.lang.IllegalArgumentException: Out of bounds: (1184, 332) for region (x=1152 y=320 w=32 h=32)
	at org.terasology.world.generation.facets.base.BaseFacet2D.getWorldIndex(BaseFacet2D.java:55) ~[classes/:na]
	at org.terasology.world.generation.facets.base.BaseFieldFacet2D.getWorld(BaseFieldFacet2D.java:48) ~[classes/:na]
	at org.terasology.cities.walls.TownWallRasterizer$1.apply(TownWallRasterizer.java:55) ~[na:na]
	at org.terasology.cities.raster.Pens$2.draw(Pens.java:64) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawClippedLine(RasterUtil.java:166) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawLine(RasterUtil.java:147) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.rasterSolid(TownWallRasterizer.java:79) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.generateChunk(TownWallRasterizer.java:64) ~[na:na]
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:67) ~[classes/:na]
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:75) ~[classes/:na]
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:661) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:08:18.839 [Chunk-Generator-4] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-4
java.lang.IllegalArgumentException: Out of bounds: (1184, 332) for region (x=1152 y=320 w=32 h=32)
	at org.terasology.world.generation.facets.base.BaseFacet2D.getWorldIndex(BaseFacet2D.java:55) ~[classes/:na]
	at org.terasology.world.generation.facets.base.BaseFieldFacet2D.getWorld(BaseFieldFacet2D.java:48) ~[classes/:na]
	at org.terasology.cities.walls.TownWallRasterizer$1.apply(TownWallRasterizer.java:55) ~[na:na]
	at org.terasology.cities.raster.Pens$2.draw(Pens.java:64) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawClippedLine(RasterUtil.java:166) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawLine(RasterUtil.java:147) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.rasterSolid(TownWallRasterizer.java:79) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.generateChunk(TownWallRasterizer.java:64) ~[na:na]
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:67) ~[classes/:na]
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:75) ~[classes/:na]
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:661) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:08:18.943 [Chunk-Generator-1] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-1
java.lang.IllegalArgumentException: Out of bounds: (1184, 332) for region (x=1152 y=320 w=32 h=32)
	at org.terasology.world.generation.facets.base.BaseFacet2D.getWorldIndex(BaseFacet2D.java:55) ~[classes/:na]
	at org.terasology.world.generation.facets.base.BaseFieldFacet2D.getWorld(BaseFieldFacet2D.java:48) ~[classes/:na]
	at org.terasology.cities.walls.TownWallRasterizer$1.apply(TownWallRasterizer.java:55) ~[na:na]
	at org.terasology.cities.raster.Pens$2.draw(Pens.java:64) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawClippedLine(RasterUtil.java:166) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawLine(RasterUtil.java:147) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.rasterSolid(TownWallRasterizer.java:79) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.generateChunk(TownWallRasterizer.java:64) ~[na:na]
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:67) ~[classes/:na]
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:75) ~[classes/:na]
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:661) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:08:19.043 [Chunk-Generator-6] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-6
java.lang.IllegalArgumentException: Out of bounds: (1184, 332) for region (x=1152 y=320 w=32 h=32)
	at org.terasology.world.generation.facets.base.BaseFacet2D.getWorldIndex(BaseFacet2D.java:55) ~[classes/:na]
	at org.terasology.world.generation.facets.base.BaseFieldFacet2D.getWorld(BaseFieldFacet2D.java:48) ~[classes/:na]
	at org.terasology.cities.walls.TownWallRasterizer$1.apply(TownWallRasterizer.java:55) ~[na:na]
	at org.terasology.cities.raster.Pens$2.draw(Pens.java:64) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawClippedLine(RasterUtil.java:166) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawLine(RasterUtil.java:147) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.rasterSolid(TownWallRasterizer.java:79) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.generateChunk(TownWallRasterizer.java:64) ~[na:na]
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:67) ~[classes/:na]
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:75) ~[classes/:na]
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:661) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:08:19.291 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.logic.location.LocationComponent) over an existing component for entity 10641
```

It also happened again later from an L&S world, seemingly in the city I started in:

```
15:13:15.625 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.logic.location.LocationComponent) over an existing component for entity 381
15:13:17.660 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1160), capping to 1000
15:13:17.669 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.logic.location.LocationComponent) over an existing component for entity 382
15:13:17.669 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.logic.location.LocationComponent) over an existing component for entity 383
15:13:18.056 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.logic.location.LocationComponent) over an existing component for entity 384
15:13:18.332 [Chunk-Generator-2] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-2
java.lang.IllegalArgumentException: Out of bounds: (89, 128) for region (x=64 y=96 w=32 h=32)
	at org.terasology.world.generation.facets.base.BaseFacet2D.getWorldIndex(BaseFacet2D.java:55) ~[classes/:na]
	at org.terasology.world.generation.facets.base.BaseFieldFacet2D.getWorld(BaseFieldFacet2D.java:48) ~[classes/:na]
	at org.terasology.cities.walls.TownWallRasterizer$1.apply(TownWallRasterizer.java:55) ~[na:na]
	at org.terasology.cities.raster.Pens$2.draw(Pens.java:64) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawClippedLine(RasterUtil.java:166) ~[na:na]
	at org.terasology.cities.raster.RasterUtil.drawLine(RasterUtil.java:147) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.rasterSolid(TownWallRasterizer.java:79) ~[na:na]
	at org.terasology.cities.walls.TownWallRasterizer.generateChunk(TownWallRasterizer.java:64) ~[na:na]
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:67) ~[classes/:na]
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:75) ~[classes/:na]
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:661) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:13:19.022 [Chunk-Generator-5] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-5
```

I don't know if this relates but I found this monstrosity in said starting city:

![terasology-150919151457-1152x720](https://cloud.githubusercontent.com/assets/1063833/9977890/d126041a-5ee5-11e5-8e57-cb8c25f819ce.jpg)

Finally an entirely different quirk - the openings left in buildings seem to contain invisible unbreakable blocks you can't move through. In this screenie I broke the top block from a 1-block opening (window maybe? Broken glass block instead?) yet couldn't move through as the lower block acted solid. Couldn't interact with it, place a block there, etc. Same for the other openings. Break normal wall and you get normal openings you can walk through

![terasology-150919151104-1152x720](https://cloud.githubusercontent.com/assets/1063833/9977900/27f35a7c-5ee6-11e5-9499-450cf1111009.jpg)

**Comment by Cervator** [comment]
Closing as mostly fixed - church is intact again, house openings are behaving, and I can't find any chunk thread crashing :-)

City walls are still a little funny, can find houses outside, but that's minor and visible so hardly likely to be forgotten. Also spotting weirdness in the gate generation, some roads get no gate while I saw one for a patch of sand - figuring it was a lake that generated too small to have any actual water :D
